CREATE
(six:Library {id: 'six'}),
(pandas:Library {id: 'pandas'}),
(numpy:Library {id: 'numpy'}),
(python_dateutil:Library {id: 'python-dateutil'}),
(pytz:Library {id: 'pytz'}),
(pyspark:Library {id: 'pyspark'}),
(matplotlib:Library {id: 'matplotlib'}),
(spacy:Library {id: 'spacy'}),
(py4j:Library {id: 'py4j'}),
(jupyter:Library {id: 'jupyter'}),
(jpy_console:Library {id: 'jpy-console'}),
(nbconvert:Library {id: 'nbconvert'}),
(ipykernel:Library {id: 'ipykernel'}),
(jpy_client:Library {id: 'jpy-client'}),
(jpy_core:Library {id: 'jpy-core'})


CREATE
(pandas)-[:DEPENDS_ON]->(numpy),
(pandas)-[:DEPENDS_ON]->(pytz),
(pandas)-[:DEPENDS_ON]->(python_dateutil),
(python_dateutil)-[:DEPENDS_ON]->(six),
(pyspark)-[:DEPENDS_ON]->(py4j),
(matplotlib)-[:DEPENDS_ON]->(numpy),
(matplotlib)-[:DEPENDS_ON]->(python_dateutil),
(matplotlib)-[:DEPENDS_ON]->(six),
(matplotlib)-[:DEPENDS_ON]->(pytz),
(spacy)-[:DEPENDS_ON]->(six),
(spacy)-[:DEPENDS_ON]->(numpy),
(jupyter)-[:DEPENDS_ON]->(nbconvert),
(jupyter)-[:DEPENDS_ON]->(ipykernel),
(jupyter)-[:DEPENDS_ON]->(jpy_console),
(jpy_console)-[:DEPENDS_ON]->(jpy_client),
(jpy_console)-[:DEPENDS_ON]->(ipykernel),
(jpy_client)-[:DEPENDS_ON]->(jpy_core),
(nbconvert)-[:DEPENDS_ON]->(jpy_core)
