PREFIX nobel: <http://data.nobelprize.org/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?p
WHERE {
  ?s rdfs:label "Bob Dylan" .
  ?s nobel:nobelPrize ?prize .
  ?prize ?p ?o .
}
ORDER BY ?p
